### ISSUE TITLE
Include entire message including FeedMessage in the output

### ISSUE THREAD

**Issue by johnhelmuth-st** [derhuerst/print-gtfs-rt-cli#5]
I would like to use this tool to be able to look at the `FeedMessage` field `header` and its properties.

It would be great to add a command line option, like `include-feed-message` to enable this.

**Comment by johnhelmuth-st** [comment]
I decided "include-all" made more sense than "include-feed-message", coded appropriately.

**Comment by derhuerst** [comment]
Fixed as of `print-gtfs-rt-cli@3.1.0`. 🎉
